name: cw_trainer
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.2 <4.0.0'

dependencies:
  audio_service: ^0.18.13
  audio_session: ^0.1.19
  characters: ^1.3.0
  flutter:
    sdk: flutter
  flutter_pcm_sound: ^1.2.2
  flutter_tts: ^4.0.2
  intl: ^0.19.0
  just_audio: ^0.9.38
  logging: ^1.2.0
  path_provider: ^2.1.3
  provider: ^6.1.2
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  test: ^1.25.2
  flutter_launcher_icons: ^0.14.0

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: "launcher_icons"
  image_path: "assets/cw_icon.png"
  min_sdk_android: 33
  ios: true
